[tool.poetry]
name = "bayreg"
version = "0.1.1"
description = ""
authors = ["Devin D. Garcia"]
license = "BSD 3-Clause"
readme = "README.md"
packages = [{include = "bayes_reg"}]
keywords = ["bayesian", "regression", "conjugate", "linear"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scipy = "^1.10.0"
scikit-learn = "^1.2.1"
numpy = "^1.23.5"
pandas = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

