[project]
name = "bayreg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numba>=0.61.2",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
